Navbara potterhead logosu eklendi
Potterhead/app pull request #20
Opened 2020-05-19 09:24 UTC by SafaElmali

<img src="https://i.ibb.co/z68rjMf/Screenshot-2020-05-19-at-12-21-32-PM.png" alt="Screenshot-2020-05-19-at-12-21-32-PM" border="0">

2020-05-19 18:03 UTC, ferhatbostanci approved these changes

2020-05-19 18:03 UTC, ferhatbostanci commented on navbar.php
> +                        <a class="nav-link <?php if ($_SERVER['REQUEST_URI'] == '/index.php') {
`if ($_SERVER['REQUEST_URI'] == '/index.php') echo 'active';` olarak düzenlersen daha iyi olur.

2020-05-19 18:07 UTC, ferhatbostanci requested changes

2020-05-19 18:07 UTC, ferhatbostanci commented on navbar.php
> +                <img src="assets/images/menu-logo.png" style="width:220px" alt="potterhead_logo">
resimlerin alt etiketlerinde `_` kullanılmıyor

2020-05-19 18:11 UTC, SafaElmali commented on navbar.php
> +                <img src="assets/images/menu-logo.png" style="width:220px" alt="potterhead_logo">
Düzenleyip yolladım :)

2020-05-19 18:12 UTC, ferhatbostanci commented on navbar.php
> +                        <a class="nav-link <?php if ($_SERVER['REQUEST_URI'] == '/index.php') { echo 'active'; } ?>" href="index.php">Anasayfa</a>
If tek satır kullanımında { } gerek duymuyor (opsiyonel)
İlgili örnek: https://www.php.net/manual/tr/control-structures.if.php#81698

2020-05-19 18:13 UTC, ferhatbostanci approved these changes

2020-05-19 18:13 UTC, ferhatbostanci approved these changes

2020-05-19 18:17 UTC, SafaElmali commented on navbar.php
> +                        <a class="nav-link <?php if ($_SERVER['REQUEST_URI'] == '/index.php') { echo 'active'; } ?>" href="index.php">Anasayfa</a>
Oraya karışmadım aslında ben ama isterseniz değiştirebilirim :)

2020-05-19 18:28 UTC, ferhatbostanci commented on navbar.php
> +                        <a class="nav-link <?php if ($_SERVER['REQUEST_URI'] == '/index.php') { echo 'active'; } ?>" href="index.php">Anasayfa</a>
Değiştirirsen güzel olur. Emir abi ¾'de bu kullanımıda gösterir hem.

2020-05-19 18:55 UTC, ferhatbostanci approved these changes

2020-05-19 19:02 UTC, SafaElmali commented on navbar.php
> +                        <a class="nav-link <?php if ($_SERVER['REQUEST_URI'] == '/index.php') { echo 'active'; } ?>" href="index.php">Anasayfa</a>
curly braces'i kaldırmak yerine ternary operator eklemesinde bulundum :)

2020-05-19 19:05 UTC, emir reviewed
Heeh beklediğim 1 commit gelmiş :) Eğitimin bu adımıyla ilgili bir tane daha beklentim kaldı, 1. yayında tam girecekken durup bunu yazıyorum, onu da yakala @SafaElmali :)

2020-05-19 19:08 UTC, SafaElmali commented
Bakayım abi inşallah :)

2020-05-19 20:09 UTC, ferhatbostanci approved these changes

2020-05-19 20:10 UTC, ferhatbostanci commented on navbar.php
> +                        <a class="nav-link <?php if ($_SERVER['REQUEST_URI'] == '/index.php') { echo 'active'; } ?>" href="index.php">Anasayfa</a>
Ahaha eline sağlık. Biraz hızlı olur diye düşünmüştüm fakat bu da anlatılır.

2020-05-20 19:30 UTC, merged

2020-05-20 19:32 UTC, emir commented
Thanks @SafaElmali🎉